import { ClientSessionProvider } from './Components/ClientSessionProvider'
import AccountModel from './Components/Account/AccountModel'
import Header from './Components/Header/Header'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Alert from './Components/Alert/Alert'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: {children: React.ReactNode}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <Header/>
          {children}
          {!session && <AccountModel/>}
          <Alert/>
        </ClientSessionProvider>
      </body>
    </html>
  )
}
